# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: PUBLISH
on: [pull_request, push]

jobs:
  build-matrix:
    strategy:
      matrix:
        mc_version: [master,1.21.6,1.21.9,1.21.11]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout ${{ matrix.mc_version }} branch
        uses: actions/checkout@v4
        with:
          ref: ${{matrix.mc_version}}
      - name: checkout repository
        uses: actions/checkout@v6
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'microsoft'
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 9.4.1
          cache-read-only: false
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: upload ${{matrix.mc_version}} artifacts
        uses: actions/upload-artifact@v7
        with:
          name: artifacts-${{ matrix.mc_version }}
          path: build/libs/*.jar
  create-release:
    needs: build-matrix
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout for source
        uses: actions/checkout@v4
      - name: Prepare release assets directory
        run: mkdir -p release-assets
      - name: Download all built JARs
        uses: actions/download-artifact@v4
        with:
          path: release-assets/
          merge-multiple: true
      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.1
          name: LostCitier ${{ github.ref_name }}
          files: release-assets/**/*
          fail_on_unmatched_files: false